global:
  interval: 1s
  color: regular
modules:
  cpu:
    interval: 2s500ms
    prefix: "\uf2db"
    postfix: 
    colors:
      good: "#75c55c"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 0-50
      warn: 51-75
      crit: 75-100
    clickEvents:
      left: urxvt -name __scratchpad -e htop 
      right: urxvt -name __scratchpad -e htop
      wheelUp: urxvt -name __scratchpad -e htop
      wheelDown: urxvt -name __scratchpad -e htop
    extra:
      key: value  
  ram:
    interval: 5s
    prefix: "\uf1b2"
    postfix: 
    colors:
      good: "#333333"
      warn: ""
      crit: ""
    levels:
      good: 0-50
      warn: 51-75
      crit: 75-100
  vpn:
    interval: 5s
    prefix:
    postfix:
    colors:
      on: "#333333"
      off: ""
  