global:
  interval: 1s
  color: regular
modules:
- title:
    interval: 1s
    prefix: "W: "
    postfix: blabla
    extra:
      maxChars: 64
- cpu:
    interval: 2s500ms
    prefix: "\uf2db"
    postfix: " :)"
    colors:
      good: "#75c55c"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 0-50
      warn: 51-75
      crit: 75-100
    clickEvents:
      left: urxvt -name __scratchpad -e htop 
      right: urxvt -name __scratchpad -e htop
      wheelUp: urxvt -name __scratchpad -e htop
      wheelDown: urxvt -name __scratchpad -e htop
    extra:
      key: value  
- exec:
    interval: 5s
    prefix: "exec: "
    clickEvents:
      left: urxvt -name __scratchpad -e ping 8.8.8.8
    extra:
      #only pipes allowed, use tee to redirect output if needed
      cmd: 'cat /proc/loadavg | awk ''{print $1}'' '
      color: "#e2c96e"
- exec:
    interval: 5s
    prefix: "vol: "
    postfix: "%"
    clickEvents:
      wheelUp: pamixer -i 2
      wheelDown: pamixer -d 2
    extra:
      #only pipes allowed, use tee to redirect output if needed
      cmd: pamixer --get-volume
      color: "#e2c96e"
- memory:
    interval: 5s
    prefix: "mem: "
    colors:
      good: "#75c55c"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 0-50
      warn: 51-75
      crit: 75-100
- time:
    interval: 5s
    prefix: "\uf133 "
    extra:
      format: 02/01 15:04
     
#  vpn:
#    interval: 5s
#    prefix:
#    postfix:
#    colors:
#      on: "#333333"
#      off: ""
  