global:
  logFile: /tmp/go3status.log
  logLevel: 3 #0 - error, 1 - warning, 2- info, 3 - debug  
modules:
- title:
    interval: 1s
    prefix: "(  "
    postfix: "  )"
    extra:
      maxChars: 64
- weather:
    interval: 15m
    extra:
      location: auto
- exec:
    prefix: "\uf188 "
    interval: 5m
    extra:
      cmd: 'P=`checkupdates|wc -l`; Y=`yay -Qua|wc -l`; echo "$P/$Y"'
      color: "#e2c96e"
      timeout: 30s
      cache: true
      update: 15m

- docker:
    interval: 5s
    prefix: " "
    postfix:
    extra:
      clientAPIVersion: "1.39"
      color: "#1bbbd2"
- exec:
    interval: 5s
    prefix: "\uf109 "
    clickEvents:
      left: urxvt -name __scratchpad -e htop
    extra:
      cmd: "cat /proc/loadavg | awk '{print $1}'"
      color: "#e2c96e"
- cpu:
    interval: 2s500ms
    prefix: "\uf2db "
    postfix: 
    colors:
      good: "#66b266"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 0-50
      warn: 51-75
      crit: 75-100
    clickEvents:
      left: urxvt -name __scratchpad -e htop 
      right: urxvt -name __scratchpad -e htop
      wheelUp: urxvt -name __scratchpad -e htop
      wheelDown: urxvt -name __scratchpad -e htop
    extra:
      key: value  
- memory:
    interval: 5s
    prefix: " "
    colors:
      good: "#66b266"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 0-50
      warn: 51-75
      crit: 75-100
    extra:
      format: '{{printf "%.1f" $used}}/{{printf "%.1f" $total}} ({{printf "%.0f" $percentage}}%)'
- hdd:
    interval: 10s
    prefix: "\uf120 " 
    postfix: 
    colors:
      good: "#66b266"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 0-60
      warn: 61-80
      crit: 81-100
    clickEvents:
      left: thunar
    extra:
      mountPoint: /
      format: '{{printf "%.1f" $avail}}'
- hdd:
    interval: 10s
    prefix: " " 
    postfix: 
    colors:
      good: "#66b266"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 0-80
      warn: 81-95
      crit: 96-100
    clickEvents:
      left: thunar
    extra:
      mountPoint: /home/kgs/storage
      # $avail, $path, $percentage  also available as float64
      format: '{{printf "%.1f" $avail}}'
- exec:
    interval: 10s
    prefix: "\uf027 "
    postfix: "%"
    clickEvents:
      left: pamixer --set-volume 0
      right: pamixer --set-volume 100
      wheelUp: pamixer -i 2
      wheelDown: pamixer -d 2
    extra:
      cmd: pamixer --get-volume|xargs -n1 echo
      color: "#e2c96e"
- batt:
    interval: 10s
    colors:
      good: "#66b266"
      warn: "#e2c96e"
      crit: "#7f0909"
    levels:
      good: 50-100
      warn: 20-50
      crit: 0-20
- exec:
    interval: 1s
    prefix: "\uf11c "
    postfix: ""
    clickEvents:
      left: xkb-switch -n
      right: xkb-switch -n
    extra:
      cmd: xkblayout
      color: "#1bbbd2" 
- time:
    interval: 1s
    prefix: "\uf274 "
    extra:
      format: 02/01 15:04
    clickEvents:
      left: 'xdg-open "https://calendar.google.com"'
      right: 'xdg-open "https://calendar.google.com"'
